### ISSUE TITLE
Pipe character in file name does not work on Win7

### ISSUE THREAD

**Issue by troussej** [ndepaola/mpc-scryfall#1]
Hi,

I ran the script on Windows 7 with 1 entry in cards.txt, and had the following error:

```
E:\Proxies\mpc-scryfall\mpc-scryfall-master>python scryfall_formatter.py
Processing: Farseek
Traceback (most recent call last):
  File "scryfall_formatter.py", line 151, in <module>
    process_card(cardname)
  File "scryfall_formatter.py", line 143, in process_card
    imageio.imwrite("formatted/" + cardname + "|" +
  File "Z:\Program Files (x86)\Python38-32\lib\site-packages\imageio\core\functions.py", line 302, in imwrite
    writer = get_writer(uri, format, "i", **kwargs)
  File "Z:\Program Files (x86)\Python38-32\lib\site-packages\imageio\core\functions.py", line 230, in get_writer
    return format.get_writer(request)
  File "Z:\Program Files (x86)\Python38-32\lib\site-packages\imageio\core\format.py", line 178, in get_writer
    return self.Writer(self, request)
  File "Z:\Program Files (x86)\Python38-32\lib\site-packages\imageio\core\format.py", line 214, in __init__
    self._open(**self.request.kwargs.copy())
  File "Z:\Program Files (x86)\Python38-32\lib\site-packages\imageio\plugins\pillow.py", line 358, in _open
    PillowFormat.Writer._open(self)
  File "Z:\Program Files (x86)\Python38-32\lib\site-packages\imageio\plugins\pillow.py", line 197, in _open
    self._fp = self.request.get_file()
  File "Z:\Program Files (x86)\Python38-32\lib\site-packages\imageio\core\request.py", line 349, in get_file
    self._file = open(self.filename, "wb")
OSError: [Errno 22] Invalid argument: 'E:\\Proxies\\mpc-scryfall\\mpc-scryfall-master\\formatted\\Farseek|C19.png'
```

I replaced the pipe character at line 143 in scryfall_formater.py and it worked.

**Comment by ndepaola** [comment]
Sorry about this! I rushed the last commit a bit and only tested it on my macOS machine. This'll be fixed in the next commit :)

**Comment by ndepaola** [comment]
fixed in most recent update
